# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Muz'), ('F', 'Zena')], max_length=1, verbose_name='pohlavi')),
                ('name', models.CharField(max_length=255, verbose_name='jmeno zakaznika')),
                ('surname', models.CharField(max_length=255, verbose_name='prijmeni')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='prezdivka')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
            ],
        ),
    ]
